name: 🏗️ Publish CocoaPods
run-name: Publish CocoaPods ${{ github.ref_name }}

on: 
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version build'
        required: false
        type: string

jobs:
  publish:
    name: Publish Affise SDK CocoaPods
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # Version
      - name: Version Tag
        id: version_tag
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo Version: ${{ inputs.version }}
            echo "VERSION=${{ inputs.version }}" >> "$GITHUB_OUTPUT"
          else
            echo Version: ${{ github.ref_name }}
            echo "VERSION=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Pod trunk me
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN  }}
        run: |
          pod trunk me

      - name: Info
        if: ${{ !cancelled() }}
        env:
          LIB_VERSION: ${{ steps.version_tag.outputs.VERSION }}
        run: |
          pod --version
          pod ipc spec AffiseAttributionLib.podspec
          pod ipc spec AffiseSKAdNetwork.podspec
          pod ipc spec AffiseInternal.podspec
          pod ipc spec AffiseModule.podspec

      # Publish
      - name: Publish AffiseAttributionLib Release
        if: ${{ !cancelled() }}
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN  }}
          LIB_VERSION: ${{ steps.version_tag.outputs.VERSION }}
        run: |
          pod trunk push AffiseAttributionLib.podspec --allow-warnings

      # Publish
      - name: Publish AffiseSKAdNetwork Release
        if: ${{ !cancelled() }}
        id: skad
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN  }}
          LIB_VERSION: ${{ steps.version_tag.outputs.VERSION }}
        run: |
          pod trunk push AffiseSKAdNetwork.podspec --allow-warnings

      # Publish
      - name: Publish AffiseInternal Release
        if: ${{ !cancelled() }}
        id: internal
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN  }}
          LIB_VERSION: ${{ steps.version_tag.outputs.VERSION }}
        run: |
          pod trunk push AffiseInternal.podspec --allow-warnings --synchronous

      # Publish
      - name: Publish AffiseModule Release
        if: ${{ !cancelled() }}
        id: module
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN  }}
          LIB_VERSION: ${{ steps.version_tag.outputs.VERSION }}
        run: |
          pod trunk push AffiseModule.podspec --allow-warnings --synchronous

      - name: Tg Release failed
        continue-on-error: true
        id: tg_failed
        if: ${{ failure() }}
        uses: cbrgm/telegram-github-action@v1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          parse-mode: markdown
          disable-web-page-preview: true
          message: |
            🔴 iOS ${{ steps.version_tag.outputs.VERSION }} release failed

            [Github Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Tg Release
        continue-on-error: true
        id: tg_success
        if: ${{ success() }}
        uses: cbrgm/telegram-github-action@v1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          parse-mode: markdown
          disable-web-page-preview: true
          message: |
            🟢 iOS ${{ steps.version_tag.outputs.VERSION }} release

            [Changelog](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md)