name: Publish
run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish Affise SDK CocoaPods
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Info
        if: ${{ success() || failure() }}
        env:
          LIB_VERSION: ${{ github.ref_name }}
        run: |
          pod --version
          pod ipc spec AffiseAttributionLib.podspec
          pod ipc spec AffiseSKAdNetwork.podspec
          pod ipc spec AffiseInternal.podspec
          pod ipc spec AffiseModule.podspec

      # Publish
      - name: Publish AffiseAttributionLib Release
        if: ${{ success() || failure() }}
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN  }}
          LIB_VERSION: ${{ github.ref_name }}
        run: |
          pod trunk push AffiseAttributionLib.podspec --allow-warnings

      # Publish
      - name: Publish AffiseSKAdNetwork Release
        if: ${{ success() || failure() }}
        id: skad
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN  }}
          LIB_VERSION: ${{ github.ref_name }}
        run: |
          pod trunk push AffiseSKAdNetwork.podspec --allow-warnings

      # Publish
      - name: Publish AffiseInternal Release
        if: ${{ success() || failure() }}
        id: internal
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN  }}
          LIB_VERSION: ${{ github.ref_name }}
        run: |
          pod trunk push AffiseInternal.podspec --allow-warnings --synchronous

      # Publish
      - name: Publish AffiseModule Release
        if: ${{ success() || failure() }}
        id: module
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN  }}
          LIB_VERSION: ${{ github.ref_name }}
        run: |
          pod trunk push AffiseModule.podspec --allow-warnings --synchronous

      # Release
      - name: Release
        if: ${{ success() || failure() }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Affise Attribution iOS SDK ${{ github.ref }}
          draft: false
          prerelease: false
